export default () => {
	return `
		<table class="pure-table">
			<thead>
				<tr>
					<th>#</th>
					<th>Make</th>
					<th>Model</th>
					<th>Year</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>1</td>
					<td>Honda</td>
					<td>Accord</td>
					<td>2000</td>
				</tr>
				<tr>
					<td>2</td>
					<td>Toyota</td>
					<td>Camry</td>
					<td>2012</td>
				</tr>
				<tr>
					<td>3</td>
					<td>Hyundai</td>
					<td>Elantra</td>
					<td>2010</td>
				</tr>
			</tbody>
		</table>
		<table class="pure-table pure-table-bordered">
			<thead>
				<tr>
					<th>#</th>
					<th>Make</th>
					<th>Model</th>
					<th>Year</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>1</td>
					<td>Honda</td>
					<td>Accord</td>
					<td>2000</td>
				</tr>
				<tr>
					<td>2</td>
					<td>Toyota</td>
					<td>Camry</td>
					<td>2012</td>
				</tr>
				<tr>
					<td>3</td>
					<td>Hyundai</td>
					<td>Elantra</td>
					<td>2010</td>
				</tr>
			</tbody>
		</table>
		<table class="pure-table pure-table-horizontal">
			<thead>
				<tr>
					<th>#</th>
					<th>Make</th>
					<th>Model</th>
					<th>Year</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>1</td>
					<td>Honda</td>
					<td>Accord</td>
					<td>2000</td>
				</tr>
				<tr>
					<td>2</td>
					<td>Toyota</td>
					<td>Camry</td>
					<td>2012</td>
				</tr>
				<tr>
					<td>3</td>
					<td>Hyundai</td>
					<td>Elantra</td>
					<td>2010</td>
				</tr>
			</tbody>
		</table>
		<table class="pure-table pure-table-striped">
			<thead>
				<tr>
					<th>#</th>
					<th>Make</th>
					<th>Model</th>
					<th>Year</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>1</td>
					<td>Honda</td>
					<td>Accord</td>
					<td>2000</td>
				</tr>
				<tr>
					<td>2</td>
					<td>Toyota</td>
					<td>Camry</td>
					<td>2012</td>
				</tr>
				<tr>
					<td>3</td>
					<td>Hyundai</td>
					<td>Elantra</td>
					<td>2010</td>
				</tr>
				<tr>
					<td>4</td>
					<td>Hello</td>
					<td>World</td>
					<td>2012</td>
				</tr>
				<tr>
					<td>5</td>
					<td>assert</td>
					<td>Hasdasd</td>
					<td>2017</td>
				</tr>
				<tr>
					<td>6</td>
					<td>JadeStrong</td>
					<td>lower</td>
					<td>2010</td>
				</tr>
				<tr>
					<td>7</td>
					<td>John</td>
					<td>weqqwe</td>
					<td>2011</td>
				</tr>
			</tbody>
		</table>
	`;
};